config/routes.rb
Rails.application.routes.draw do
  resources :games
  root 'posts#index'
  devise_for :users
  resources :posts do
    resources :comments
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/games_controller.rb
require_relative  './games_tt.rb'
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    @boardId = params["boardId"]
    logger.debug "board : #{params["master"]} "
    @master = GameMaster.new(params[:player1],params[:player2])
    @master.game.go(@boardId.to_i + 1)
    @game.board = @master.board.board
    logger.debug "Person attributes hash: #{params["boardId"]} #{@master.board.board}"
    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game.id), notice: 'board is updated for position.' + @boardId.to_s }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { redirect_to game_url(@game.id), notice: 'Game was successfully created. #{@boardId}' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.board = [ "X","O","X","O"," ","O","O","O","O" ]

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game.id), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    @dummyBoard = [ "","","",""," ","","","","" ]
    respond_to do |format|      
      if @game.update_attributes(:board => @dummyBoard)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:player1, :player2)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player1 %><br>
    <%= f.text_field :player1 %>
  </div>
  <div class="field">
    <%= f.label :player2 %><br>
    <%= f.text_field :player2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Player1</th>
      <th>Player2</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.player1 %></td>
        <td><%= game.player2 %></td>
        <td><%= game.board %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player1:</strong>
  <%= @game.player1 %>
</p>

<p>
  <strong>Player2:</strong>
  <%= @game.player2 %>
</p>

<p>
  <strong>Board:</strong>
  <%= @game.board %>
</p>

<%= link_to 'Back', games_path %>

 <div id="tic-tac-toe game ">
<div class="span5 new_span">
<div class="row">
<h1 class="span3">Tic Tac Toe</h1>
<div class="span3">
<div class="input-prepend input-append">
    <span class="add-on win_text">O won</span><strong id="o_win" class="win_times add-on">0</strong><span class="add-on">time(s)</span>
    </div>
    <div class="input-prepend input-append">
    <span class="add-on win_text">X won</span><strong id="x_win" class="win_times add-on">0</strong><span class="add-on">time(s)</span>
    </div>
      
</div>


    
</div>
<ul class="row" id="game">
 <% eval(@game.board).each_with_index do |i,index| %>
                <%="<li id='i#{index}' class='btn span1'>".html_safe%>
                    <%= i || 'null' %>                    
                    <%= link_to 'Edit', edit_game_path(@game, :boardId => index) %>
                <%=%>
 <%end%>
</ul>
<div class="clr">&nbsp;</div>
<div class="row"><a href="#" id="reset" class="btn-success btn span3" >Restart</a></div></div>
</div>