config/routes.rb
Rails.application.routes.draw do
  resources :games
  root 'posts#index'
  devise_for :users
  resources :posts do
    resources :comments
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :users
  has_many :comments, dependent: :destroy
  validates_presence_of :title
  validates_presence_of :body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:destroy, :edit]
  #before_action :authenticate, expection: [:index,:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find(@post.user_id)
  end
  # DELETE /posts/1
  # DELETE /posts/1.json

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
 

  def check_auth

     if current_user.id != @post.user_id
        redirect_to posts_path
        flash[:notice] = " sorry buddy you cannot do that"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
    def authenticate
      authenticate_or_request_with_http_basic do |name,password|
        name == "admin" && password == "secret"
      end

    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>The world of Ideas</h1>

<table class="table table-striped" >
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.reverse.each do |post| %>
      <tr >
        <td class="active"><a href='posts/<%=	post.id  %>'><%=  post.title %></a></td>        
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        
        <td ><%= link_to 'Destroy',post, :method => :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button class="btn btn-default" type="submit">
<%= link_to 'New Post', new_post_path %>
</button>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="hero-unit">
<p>
  Posted by <%= @user.email %>
  </br>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong></strong>
  <%= simple_format(@post.body) %>
</p>
</div>

<h2>Comments</h2>
<div id="comments">
   <%= render :partial => @post.comments.reverse %>
</div>
 
<%= form_for([@post, Comment.new], remote: true) do |f| %>
    <p><%= f.label :body, "New comment" %>
    <br/>
    <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit "Add comment", :id => 'add_comment'%>
    </p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>  
<script type="text/javascript">
  $(document).ready(function(){
   $('#add_comment').attr('disabled', true);
   $('#comment_body').on('keyup',function() {
    if($(this).val() != '') {
        $('#add_comment').attr('disabled' , false);
        
    }else{
        $('#add_comment').attr('disabled' , true);
    }

   });
 });
</script>